<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import toml from 'smol-toml'
import { ElMessage } from 'element-plus'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const assistantPromptTool = ref<AssistantPromptTool>('codex'); const assistantConfigFile = ref<AssistantConfigFile>('prompt'); const assistantConfigContent = ref(''); const assistantConfigPath = ref(''); const assistantConfigExists = ref(false); const assistantConfigBusy = ref(false); const assistantConfigMessage = ref('选择助手和文件后读取本机全局配置。'); const backToPortal = () => router.push({ name: 'portal' })
const assistantToolLabel = computed(() => ({ codex: 'Codex', cursor: 'Cursor', 'claude-code': 'Claude Code' })[assistantPromptTool.value]); const assistantFileLabel = computed(() => assistantConfigFile.value === 'prompt' ? '全局提示词' : '配置文件')
const loadAssistantConfig = async () => { if (!window.assistantConfig) { assistantConfigMessage.value = '请重启应用以加载 AI 配置组件'; return } assistantConfigBusy.value = true; try { const result = await window.assistantConfig.read(assistantPromptTool.value, assistantConfigFile.value); assistantConfigContent.value = result.content; assistantConfigPath.value = result.path; assistantConfigExists.value = result.exists; assistantConfigMessage.value = result.exists ? `已读取 ${assistantFileLabel.value}。` : '文件尚不存在；保存后会在对应全局目录创建。' } catch (error) { assistantConfigMessage.value = error instanceof Error ? error.message : String(error) } finally { assistantConfigBusy.value = false } }
const saveAssistantConfig = async () => { if (!window.assistantConfig) return; try { if (assistantConfigFile.value === 'config') { if (assistantPromptTool.value === 'codex') toml.parse(assistantConfigContent.value); else JSON.parse(assistantConfigContent.value) } } catch (error) { assistantConfigMessage.value = `配置格式无效，未保存：${error instanceof Error ? error.message : String(error)}`; return } const action = assistantConfigExists.value ? '覆盖保存' : '创建并保存'; if (!window.confirm(`确认${action} ${assistantToolLabel.value} 的${assistantFileLabel.value}吗？`)) return; assistantConfigBusy.value = true; try { const result = await window.assistantConfig.save(assistantPromptTool.value, assistantConfigFile.value, assistantConfigContent.value); assistantConfigPath.value = result.path; assistantConfigExists.value = true; assistantConfigMessage.value = `已保存到 ${result.path}`; ElMessage.success({ message: '已保存全局配置', duration: 1_800 }) } catch (error) { assistantConfigMessage.value = error instanceof Error ? error.message : String(error) } finally { assistantConfigBusy.value = false } }
void loadAssistantConfig()
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>数据工具 / AI CODING ASSISTANTS</p><h2>AI 提示词与配置</h2><span>在本机直接维护 Codex、Cursor 和 Claude Code 的全局提示词与配置文件。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="assistant-config-card"><div class="assistant-config-controls"><label>AI 编程助手<select v-model="assistantPromptTool" :disabled="assistantConfigBusy" @change="loadAssistantConfig"><option value="codex">Codex</option><option value="cursor">Cursor</option><option value="claude-code">Claude Code</option></select></label><label>编辑内容<select v-model="assistantConfigFile" :disabled="assistantConfigBusy" @change="loadAssistantConfig"><option value="prompt">全局提示词</option><option value="config">配置文件</option></select></label><button :disabled="assistantConfigBusy" @click="loadAssistantConfig">{{ assistantConfigBusy ? '读取中…' : '重新读取' }}</button><button class="primary" :disabled="assistantConfigBusy" @click="saveAssistantConfig">{{ assistantConfigBusy ? '处理中…' : '保存到全局' }}</button></div><p class="tool-message" :class="{ error: assistantConfigMessage.includes('失败') || assistantConfigMessage.includes('无效') }">{{ assistantConfigMessage }}</p><p class="assistant-config-path"><small>文件位置</small><code>{{ assistantConfigPath || '读取后显示' }}</code></p><label class="assistant-config-editor"><span>{{ assistantToolLabel }} · {{ assistantFileLabel }}</span><textarea v-model="assistantConfigContent" spellcheck="false" :placeholder="assistantConfigFile === 'prompt' ? '输入适用于所有项目的指令…' : '输入配置文件内容…'"></textarea></label><p class="assistant-config-note">保存前会校验 JSON/TOML 配置，并将原文件备份为同目录的 <code>.bak</code> 文件。Cursor 的本机全局规则保存为 <code>~/.cursor/rules/global.mdc</code>。</p></section></ToolboxPage></template>
