<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
import SvgIcon from '../components/SvgIcon.vue'
const router = useRouter(); const imageInput = ref<HTMLInputElement>(); const imagePreviewUrl = ref(''); const imageFile = ref<File>(); const imageInfo = ref<{ width: number; height: number }>(); const imageMessage = ref('选择一张本地图片后，可预览并导出 PNG 或 JPEG。'); const backgroundTolerance = ref(36); const imageProcessing = ref(false); const compressedImage = ref<{ url: string; blob: Blob; format: string }>(); const maxImageFileSize = 100 * 1024 * 1024; const maxImagePixels = 12_000_000
const backToPortal = () => router.push({ name: 'portal' }); const openImagePicker = () => imageInput.value?.click(); const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 ** 2 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 ** 2).toFixed(2)} MB`; const isSupportedImageFile = (file: File) => file.type.startsWith('image/') || /\.(png|jpe?g|webp|gif|bmp|svg)$/i.test(file.name)
const clearCompressedImage = () => { if (compressedImage.value?.url) URL.revokeObjectURL(compressedImage.value.url); compressedImage.value = undefined }
const loadCanvasImage = (url: string): Promise<HTMLImageElement> => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('图片加载失败')); image.src = url })
const loadImage = (file?: File) => { if (!file || !isSupportedImageFile(file)) { imageMessage.value = '请选择图片文件。'; return } if (file.size > maxImageFileSize) { imageMessage.value = '单张图片不能超过 100 MB。'; return } if (imagePreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(imagePreviewUrl.value); clearCompressedImage(); imageFile.value = file; imagePreviewUrl.value = URL.createObjectURL(file); const image = new Image(); image.onload = () => { if (!image.naturalWidth || !image.naturalHeight || image.naturalWidth * image.naturalHeight > maxImagePixels) { imageMessage.value = '图片像素过大，请使用不超过 1200 万像素的图片。'; imageFile.value = undefined; imageInfo.value = undefined; return } imageInfo.value = { width: image.naturalWidth, height: image.naturalHeight }; imageMessage.value = '图片已加载，所有处理仅在本机完成。' }; image.onerror = () => { imageMessage.value = '图片无法加载。请确认文件未损坏。' }; image.src = imagePreviewUrl.value }
const onImageSelected = (event: Event) => { const input = event.target as HTMLInputElement; loadImage(input.files?.[0]); input.value = '' }; const onImageDropped = (event: DragEvent) => { const file = event.dataTransfer?.files[0]; if (file) loadImage(file) }
const removeBackground = async () => { imageProcessing.value = true; try { if (!imagePreviewUrl.value || !imageInfo.value) throw new Error('请先选择图片'); const image = await loadCanvasImage(imagePreviewUrl.value); const canvas = document.createElement('canvas'); canvas.width = imageInfo.value.width; canvas.height = imageInfo.value.height; const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) throw new Error('无法读取图片像素'); context.drawImage(image, 0, 0); const pixels = context.getImageData(0, 0, canvas.width, canvas.height); const { data } = pixels; const corners = [0, canvas.width - 1, (canvas.height - 1) * canvas.width, canvas.width * canvas.height - 1]; const colors = corners.map((pixel) => ({ r: data[pixel * 4], g: data[pixel * 4 + 1], b: data[pixel * 4 + 2] })); const distance = (left: { r: number; g: number; b: number }, right: { r: number; g: number; b: number }) => (left.r - right.r) ** 2 + (left.g - right.g) ** 2 + (left.b - right.b) ** 2; const background = colors.reduce((best, color) => colors.reduce((sum, other) => sum + distance(color, other), 0) < colors.reduce((sum, other) => sum + distance(best, other), 0) ? color : best); const threshold = backgroundTolerance.value ** 2 * 3; const queue = new Int32Array(canvas.width * canvas.height); const visited = new Uint8Array(canvas.width * canvas.height); let head = 0; let tail = 0; const enqueue = (pixel: number) => { const index = pixel * 4; if (visited[pixel]) return; const color = { r: data[index], g: data[index + 1], b: data[index + 2] }; if (data[index + 3] !== 0 && distance(color, background) > threshold) return; visited[pixel] = 1; data[index + 3] = 0; queue[tail++] = pixel }; for (let x = 0; x < canvas.width; x += 1) { enqueue(x); enqueue((canvas.height - 1) * canvas.width + x) } for (let y = 1; y < canvas.height - 1; y += 1) { enqueue(y * canvas.width); enqueue(y * canvas.width + canvas.width - 1) } while (head < tail) { const pixel = queue[head++]; const x = pixel % canvas.width; if (x > 0) enqueue(pixel - 1); if (x + 1 < canvas.width) enqueue(pixel + 1); if (pixel >= canvas.width) enqueue(pixel - canvas.width); if (pixel + canvas.width < canvas.width * canvas.height) enqueue(pixel + canvas.width) } context.putImageData(pixels, 0, 0); imagePreviewUrl.value = canvas.toDataURL('image/png'); clearCompressedImage(); imageMessage.value = '已按图片四角的背景色生成透明区域；复杂背景建议调高容差后重试。' } catch (error) { imageMessage.value = error instanceof Error ? error.message : String(error) } finally { imageProcessing.value = false } }
const compressImage = async () => { try { if (!imagePreviewUrl.value) throw new Error('请先处理图片'); const image = await loadCanvasImage(imagePreviewUrl.value); const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const context = canvas.getContext('2d'); if (!context) throw new Error('无法创建图片画布'); context.drawImage(image, 0, 0); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((result) => result ? resolve(result) : reject(new Error('图片编码失败')), 'image/png')); clearCompressedImage(); compressedImage.value = { url: URL.createObjectURL(blob), blob, format: 'image/png' }; imageMessage.value = '下载文件已生成。' } catch (error) { imageMessage.value = error instanceof Error ? error.message : String(error) } }
const downloadCompressedImage = () => { if (!compressedImage.value) return; const link = document.createElement('a'); link.href = compressedImage.value.url; link.download = `${imageFile.value?.name.replace(/\.[^.]+$/, '') ?? 'image'}-tinied.png`; link.click() }
onBeforeUnmount(() => { if (imagePreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(imagePreviewUrl.value); clearCompressedImage() })
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>设计工具 / TRANSPARENT BACKGROUND</p><h2>背景透明化</h2><span>基于图片四角的颜色移除接近的纯色背景，适合商品图和证件照。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><input ref="imageInput" class="visually-hidden" type="file" accept="image/*" @change="onImageSelected"><section class="image-dropzone" :class="{ 'has-image': imagePreviewUrl }" @click="openImagePicker" @dragover.prevent @drop.prevent="onImageDropped"><img v-if="imagePreviewUrl" :src="imagePreviewUrl" :alt="imageFile?.name ?? '图片预览'"><div v-else><SvgIcon name="image" /><strong>选择或拖入图片</strong><span>建议使用纯色背景图片</span></div></section><p class="tool-message">{{ imageMessage }}</p><section v-if="imageFile && imageInfo" class="image-workbench single-image-tool"><div><h3>去除背景</h3><p>根据四角颜色生成透明区域；复杂背景建议多次调整容差。</p><label>容差 <input v-model.number="backgroundTolerance" type="range" min="8" max="100"><output>{{ backgroundTolerance }}</output></label><button class="primary" :disabled="imageProcessing" @click="removeBackground">{{ imageProcessing ? '处理中…' : '去除背景' }}</button><button @click="compressImage">生成下载文件</button></div></section><section v-if="compressedImage && imageFile" class="compression-result"><div><small>处理结果</small><strong>{{ formatBytes(compressedImage.blob.size) }}</strong></div><button class="primary" @click="downloadCompressedImage">下载 PNG</button></section></ToolboxPage></template>
