<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const colorHex = ref('#16a34a'); const colorMessage = ref('输入或选择颜色，即可获得不同格式的颜色值。'); const backToPortal = () => router.push({ name: 'portal' })
const normalizedHex = computed(() => { const match = colorHex.value.trim().match(/^#?([\da-f]{3}|[\da-f]{6})$/i); const value = match?.[1] ?? ''; if (/^[\da-f]{3}$/i.test(value)) return `#${value.split('').map((part) => part + part).join('').toUpperCase()}`; return /^[\da-f]{6}$/i.test(value) ? `#${value.toUpperCase()}` : undefined })
const colorRgb = computed(() => { if (!normalizedHex.value) return; const value = normalizedHex.value.slice(1); return { r: Number.parseInt(value.slice(0, 2), 16), g: Number.parseInt(value.slice(2, 4), 16), b: Number.parseInt(value.slice(4, 6), 16) } })
const colorHsl = computed(() => { if (!colorRgb.value) return; const { r, g, b } = colorRgb.value; const [red, green, blue] = [r, g, b].map((part) => part / 255); const max = Math.max(red, green, blue); const min = Math.min(red, green, blue); const lightness = (max + min) / 2; const delta = max - min; if (!delta) return { h: 0, s: 0, l: Math.round(lightness * 100) }; const saturation = delta / (1 - Math.abs(2 * lightness - 1)); const hue = max === red ? ((green - blue) / delta) % 6 : max === green ? (blue - red) / delta + 2 : (red - green) / delta + 4; return { h: Math.round((hue * 60 + 360) % 360), s: Math.round(saturation * 100), l: Math.round(lightness * 100) } })
const setHex = (value: string) => { colorHex.value = value; colorMessage.value = /^#?(?:[\da-f]{3}|[\da-f]{6})$/i.test(value.trim()) ? '颜色已更新。' : '请输入 3 位或 6 位 HEX 颜色值。' }
const copyColor = async (value: string) => { await navigator.clipboard.writeText(value); colorMessage.value = `已复制 ${value}` }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>设计工具 / 颜色</p><h2>颜色转换器</h2><span>输入 HEX 颜色，快速获得 RGB 与 HSL 表示法。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="color-card"><div class="color-preview" :style="{ background: normalizedHex ?? '#eef2ef' }"></div><label>HEX 颜色<input v-model="colorHex" maxlength="7" placeholder="#16A34A" @input="setHex(colorHex)"></label><input class="color-picker" type="color" :value="normalizedHex ?? '#16a34a'" aria-label="选择颜色" @input="setHex(($event.target as HTMLInputElement).value)"><p class="tool-message" :class="{ error: !normalizedHex }">{{ colorMessage }}</p></section><section v-if="colorRgb && colorHsl && normalizedHex" class="color-values"><button type="button" @click="copyColor(normalizedHex)"><small>HEX</small><strong>{{ normalizedHex }}</strong><span>点击复制</span></button><button type="button" @click="copyColor(`rgb(${colorRgb.r}, ${colorRgb.g}, ${colorRgb.b})`)"><small>RGB</small><strong>rgb({{ colorRgb.r }}, {{ colorRgb.g }}, {{ colorRgb.b }})</strong><span>点击复制</span></button><button type="button" @click="copyColor(`hsl(${colorHsl.h}, ${colorHsl.s}%, ${colorHsl.l}%)`)"><small>HSL</small><strong>hsl({{ colorHsl.h }}, {{ colorHsl.s }}%, {{ colorHsl.l }}%)</strong><span>点击复制</span></button></section></ToolboxPage></template>
