<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import YAML from 'yaml'
import toml from 'smol-toml'
import { XMLBuilder, XMLParser, XMLValidator } from 'fast-xml-parser'
import ToolboxPage from '../ToolboxPage.vue'
type Format = 'json' | 'yaml' | 'toml' | 'xml'
const router = useRouter(); const convertSource = ref('{\n  "name": "LocalForge",\n  "local": true\n}'); const convertResult = ref(''); const convertFrom = ref<Format>('json'); const convertTo = ref<Format>('yaml'); const convertMessage = ref('选择输入与输出格式后转换；所有内容仅在本机处理。'); const backToPortal = () => router.push({ name: 'portal' })
const parseStructured = (format: Format, source: string): unknown => { if (format === 'json') return JSON.parse(source); if (format === 'yaml') return YAML.parse(source); if (format === 'toml') return toml.parse(source); const validation = XMLValidator.validate(source); if (validation !== true) throw new Error(`XML 第 ${validation.err.line} 行：${validation.err.msg}`); return new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_', parseTagValue: false, parseAttributeValue: false, trimValues: false }).parse(source) }
const stringifyStructured = (format: Format, value: unknown): string => { if (format === 'json') return JSON.stringify(value, null, Number(localStorage.getItem('localforge:json-indent')) === 4 ? 4 : 2); if (format === 'yaml') return YAML.stringify(value); if (format === 'toml') return toml.stringify(value as Record<string, unknown>); return new XMLBuilder({ ignoreAttributes: false, attributeNamePrefix: '@_', format: true, indentBy: '  ' }).build(value) }
const convertStructured = () => { try { if (!convertSource.value.trim()) throw new Error('请输入要转换的内容'); if (convertSource.value.length > 10 * 1024 * 1024) throw new Error('配置内容不能超过 10 MB'); let parsed = parseStructured(convertFrom.value, convertSource.value); if (parsed === undefined) throw new Error('输入内容为空或没有可转换的数据'); if (convertTo.value === 'xml' && convertFrom.value !== 'xml') { const isRecord = parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed); const keys = isRecord ? Object.keys(parsed as Record<string, unknown>) : []; const hasSingleUsableRoot = keys.length === 1 && /^[A-Za-z_][\w.:-]*$/.test(keys[0]) && !Array.isArray((parsed as Record<string, unknown>)[keys[0]]); if (!hasSingleUsableRoot) parsed = { root: Array.isArray(parsed) ? { item: parsed } : parsed } } convertResult.value = stringifyStructured(convertTo.value, parsed); convertMessage.value = `${convertFrom.value.toUpperCase()} 已转换为 ${convertTo.value.toUpperCase()}。` } catch (error) { convertResult.value = ''; convertMessage.value = `转换失败：${error instanceof Error ? error.message : String(error)}` } }
const copyConvertResult = async () => { if (convertResult.value) { await navigator.clipboard.writeText(convertResult.value); convertMessage.value = '转换结果已复制到剪贴板。' } }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>数据工具 / CONFIG</p><h2>配置格式转换</h2><span>在 JSON、YAML、TOML 和 XML 间进行本地转换，XML 属性保留为 <code>@_属性名</code>。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="json-actions"><label>输入格式 <select v-model="convertFrom"><option value="json">JSON</option><option value="yaml">YAML</option><option value="toml">TOML</option><option value="xml">XML</option></select></label><label>输出格式 <select v-model="convertTo"><option value="json">JSON</option><option value="yaml">YAML</option><option value="toml">TOML</option><option value="xml">XML</option></select></label><button class="primary" @click="convertStructured">开始转换</button><button :disabled="!convertResult" @click="copyConvertResult">复制结果</button></section><p class="tool-message">{{ convertMessage }}</p><section class="json-editors"><label>输入<textarea v-model="convertSource" spellcheck="false" placeholder="粘贴配置内容"></textarea></label><label>结果<textarea v-model="convertResult" spellcheck="false" readonly placeholder="转换结果会出现在这里"></textarea></label></section></ToolboxPage></template>
