<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import CryptoJS from 'crypto-js'
import { sm2, sm3, sm4 } from 'sm-crypto'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const cryptoAlgorithm = ref<'md5' | 'sha256' | 'sm3' | 'aes' | 'sm4' | 'sm2'>('md5'); const cryptoOperation = ref<'encrypt' | 'decrypt'>('encrypt'); const cryptoSource = ref('LocalForge'); const cryptoKey = ref(''); const cryptoMode = ref<'ecb' | 'cbc'>('cbc'); const cryptoIv = ref(''); const cryptoPadding = ref<'pkcs7' | 'none'>('pkcs7'); const sm2CipherMode = ref<0 | 1>(1); const sm3Key = ref(''); const cryptoPublicKey = ref(''); const cryptoPrivateKey = ref(''); const cryptoResult = ref(''); const cryptoMessage = ref('MD5、SHA-256、SM3 为摘要算法；AES、SM4、SM2 支持本地加解密。'); const backToPortal = () => router.push({ name: 'portal' })
const generateSm2Keys = () => { const pair = sm2.generateKeyPairHex(); cryptoPrivateKey.value = pair.privateKey; cryptoPublicKey.value = pair.publicKey; cryptoMessage.value = '已在本机生成 SM2 密钥对；请妥善保存私钥，离开此页面后不会保留。' }
const parseHexWordArray = (value: string, label: string, lengths: number[]) => { const normalized = value.trim(); if (!lengths.includes(normalized.length) || !/^[\da-f]+$/i.test(normalized)) throw new Error(`${label}必须是 ${lengths.join('、')} 位十六进制字符`); return CryptoJS.enc.Hex.parse(normalized) }
const runCrypto = () => {
  try {
    if (!cryptoSource.value) throw new Error('请输入待处理内容'); if (cryptoSource.value.length > 20 * 1024 * 1024) throw new Error('待处理内容不能超过 20 MB')
    if (cryptoAlgorithm.value === 'md5') cryptoResult.value = CryptoJS.MD5(cryptoSource.value).toString()
    else if (cryptoAlgorithm.value === 'sha256') cryptoResult.value = CryptoJS.SHA256(cryptoSource.value).toString()
    else if (cryptoAlgorithm.value === 'sm3') { const key = sm3Key.value.trim(); if (key && (!/^[\da-f]+$/i.test(key) || key.length % 2 !== 0)) throw new Error('SM3 HMAC 密钥必须是偶数长度的十六进制字符'); cryptoResult.value = key ? sm3(cryptoSource.value, { key }) : sm3(cryptoSource.value) }
    else if (cryptoAlgorithm.value === 'aes') { const key = parseHexWordArray(cryptoKey.value, 'AES 密钥', [32, 48, 64]); const iv = cryptoMode.value === 'cbc' ? parseHexWordArray(cryptoIv.value, 'AES IV', [32]) : undefined; const options = { mode: cryptoMode.value === 'cbc' ? CryptoJS.mode.CBC : CryptoJS.mode.ECB, padding: cryptoPadding.value === 'pkcs7' ? CryptoJS.pad.Pkcs7 : CryptoJS.pad.NoPadding, ...(iv ? { iv } : {}) }; if (cryptoPadding.value === 'none' && cryptoOperation.value === 'encrypt' && new TextEncoder().encode(cryptoSource.value).length % 16 !== 0) throw new Error('AES 无填充加密时，明文的 UTF-8 字节数必须是 16 的倍数'); if (cryptoOperation.value === 'decrypt') { const encoded = cryptoSource.value.replace(/\s/g, ''); if (!/^[A-Za-z0-9+/]+={0,2}$/.test(encoded) || encoded.length % 4 !== 0 || CryptoJS.enc.Base64.parse(encoded).sigBytes % 16 !== 0) throw new Error('AES 密文必须是有效的 Base64，解码后长度必须是 16 字节的倍数') } cryptoResult.value = cryptoOperation.value === 'encrypt' ? CryptoJS.AES.encrypt(cryptoSource.value, key, options).toString() : CryptoJS.AES.decrypt(cryptoSource.value, key, options).toString(CryptoJS.enc.Utf8); if (cryptoOperation.value === 'decrypt' && !cryptoResult.value) throw new Error('解密失败：请确认密文、密钥和参数') }
    else if (cryptoAlgorithm.value === 'sm4') { if (!/^[\da-f]{32}$/i.test(cryptoKey.value)) throw new Error('SM4 密钥必须是 32 位十六进制字符'); if (cryptoMode.value === 'cbc' && !/^[\da-f]{32}$/i.test(cryptoIv.value)) throw new Error('SM4 CBC IV 必须是 32 位十六进制字符'); if (cryptoOperation.value === 'decrypt' && (!/^[\da-f]+$/i.test(cryptoSource.value) || cryptoSource.value.length % 32 !== 0)) throw new Error('SM4 密文必须是长度为 32 倍数的十六进制字符'); if (cryptoPadding.value === 'none' && cryptoOperation.value === 'encrypt' && new TextEncoder().encode(cryptoSource.value).length % 16 !== 0) throw new Error('SM4 无填充加密时，明文的 UTF-8 字节数必须是 16 的倍数'); const options: { mode: 'ecb' | 'cbc'; padding: 'pkcs#7' | 'none'; iv?: string } = { mode: cryptoMode.value, padding: cryptoPadding.value === 'pkcs7' ? 'pkcs#7' : 'none', ...(cryptoMode.value === 'cbc' ? { iv: cryptoIv.value } : {}) }; cryptoResult.value = cryptoOperation.value === 'encrypt' ? sm4.encrypt(cryptoSource.value, cryptoKey.value, options) : sm4.decrypt(cryptoSource.value, cryptoKey.value, options) }
    else if (cryptoOperation.value === 'encrypt') { if (!cryptoPublicKey.value.trim()) throw new Error('请输入 SM2 公钥'); cryptoResult.value = sm2.doEncrypt(cryptoSource.value, cryptoPublicKey.value.trim(), sm2CipherMode.value) }
    else { if (!/^[\da-f]{64}$/i.test(cryptoPrivateKey.value.trim())) throw new Error('SM2 私钥必须是 64 位十六进制字符'); cryptoResult.value = sm2.doDecrypt(cryptoSource.value.trim(), cryptoPrivateKey.value.trim(), sm2CipherMode.value); if (!cryptoResult.value) throw new Error('SM2 解密失败：请确认密文、私钥和密文排列') }
    cryptoMessage.value = ['md5', 'sha256', 'sm3'].includes(cryptoAlgorithm.value) ? '摘要已生成。摘要不可逆，不能用于解密。' : `${cryptoOperation.value === 'encrypt' ? '加密' : '解密'}完成。`
  } catch (error) { cryptoResult.value = ''; cryptoMessage.value = `处理失败：${error instanceof Error ? error.message : String(error)}` }
}
const copyCryptoResult = async () => { if (cryptoResult.value) { await navigator.clipboard.writeText(cryptoResult.value); cryptoMessage.value = '结果已复制到剪贴板。' } }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>数据工具 / CRYPTO</p><h2>加解密工作台</h2><span>处理仅在本机完成。不要在不可信设备或页面中输入生产密钥。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="crypto-card"><div class="crypto-actions"><label>算法<select v-model="cryptoAlgorithm"><option value="md5">MD5 摘要</option><option value="sha256">SHA-256 摘要</option><option value="sm3">SM3 摘要</option><option value="aes">AES</option><option value="sm4">SM4</option><option value="sm2">SM2</option></select></label><label v-if="!['md5', 'sha256', 'sm3'].includes(cryptoAlgorithm)">操作<select v-model="cryptoOperation"><option value="encrypt">加密</option><option value="decrypt">解密</option></select></label></div><label>输入<textarea v-model="cryptoSource" spellcheck="false" placeholder="输入明文、密文或待计算摘要的内容"></textarea></label><template v-if="cryptoAlgorithm === 'aes' || cryptoAlgorithm === 'sm4'"><label>{{ cryptoAlgorithm === 'sm4' ? 'SM4 密钥（32 位十六进制）' : 'AES 密钥（32 / 48 / 64 位十六进制）' }}<input v-model="cryptoKey" type="password" spellcheck="false"></label><label>分组模式<select v-model="cryptoMode"><option value="cbc">CBC</option><option value="ecb">ECB</option></select></label><label v-if="cryptoMode === 'cbc'">初始化向量 IV（32 位十六进制）<input v-model="cryptoIv" type="password" spellcheck="false"></label><label>填充方式<select v-model="cryptoPadding"><option value="pkcs7">PKCS#7</option><option value="none">无填充（明文需为 16 字节倍数）</option></select></label></template><template v-else-if="cryptoAlgorithm === 'sm3'"><label>HMAC 密钥（可选，十六进制）<input v-model="sm3Key" type="password" spellcheck="false"></label></template><template v-else-if="cryptoAlgorithm === 'sm2'"><div class="sm2-key-actions"><button @click="generateSm2Keys">生成 SM2 密钥对</button><label>密文排列<select v-model.number="sm2CipherMode"><option :value="1">C1C3C2（推荐）</option><option :value="0">C1C2C3</option></select></label></div><p class="crypto-note">SM2 是椭圆曲线公钥加密，不使用 IV 或分组填充；互操作时需确保双方采用相同密文排列。</p><label>SM2 公钥（加密使用，支持压缩或非压缩格式）<textarea v-model="cryptoPublicKey" spellcheck="false"></textarea></label><label>SM2 私钥（解密使用）<textarea v-model="cryptoPrivateKey" spellcheck="false"></textarea></label></template><div class="crypto-run"><button class="primary" @click="runCrypto">{{ ['md5', 'sha256', 'sm3'].includes(cryptoAlgorithm) ? '生成摘要' : cryptoOperation === 'encrypt' ? '加密' : '解密' }}</button><button :disabled="!cryptoResult" @click="copyCryptoResult">复制结果</button></div><p class="tool-message">{{ cryptoMessage }}</p><label>结果<textarea v-model="cryptoResult" readonly spellcheck="false"></textarea></label></section></ToolboxPage></template>
