<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
type DiffRow = { kind: 'same' | 'add' | 'remove'; text: string }
const router = useRouter(); const diffLeft = ref('name: LocalForge\nversion: 1'); const diffRight = ref('name: LocalForge\nversion: 2\nlocal: true'); const backToPortal = () => router.push({ name: 'portal' }); const splitDiffLines = (value: string) => value ? value.split(/\r\n|\r|\n/) : []
const diffTooLarge = computed(() => splitDiffLines(diffLeft.value).length + splitDiffLines(diffRight.value).length > 2_000)
const diffRows = computed<DiffRow[]>(() => { const left = splitDiffLines(diffLeft.value); const right = splitDiffLines(diffRight.value); if (diffTooLarge.value) return []; const table = Array.from({ length: left.length + 1 }, () => new Uint16Array(right.length + 1)); for (let leftIndex = left.length - 1; leftIndex >= 0; leftIndex -= 1) for (let rightIndex = right.length - 1; rightIndex >= 0; rightIndex -= 1) table[leftIndex][rightIndex] = left[leftIndex] === right[rightIndex] ? table[leftIndex + 1][rightIndex + 1] + 1 : Math.max(table[leftIndex + 1][rightIndex], table[leftIndex][rightIndex + 1]); const rows: DiffRow[] = []; let leftIndex = 0; let rightIndex = 0; while (leftIndex < left.length && rightIndex < right.length) { if (left[leftIndex] === right[rightIndex]) { rows.push({ kind: 'same', text: left[leftIndex] }); leftIndex += 1; rightIndex += 1 } else if (table[leftIndex + 1][rightIndex] >= table[leftIndex][rightIndex + 1]) { rows.push({ kind: 'remove', text: left[leftIndex++] }) } else rows.push({ kind: 'add', text: right[rightIndex++] }) } while (leftIndex < left.length) rows.push({ kind: 'remove', text: left[leftIndex++] }); while (rightIndex < right.length) rows.push({ kind: 'add', text: right[rightIndex++] }); return rows })
const copyDiff = async () => { if (diffTooLarge.value) return; const header = `--- 原始文本\n+++ 目标文本\n@@ -1,${splitDiffLines(diffLeft.value).length} +1,${splitDiffLines(diffRight.value).length} @@`; await navigator.clipboard.writeText(`${header}\n${diffRows.value.map((row) => `${row.kind === 'add' ? '+' : row.kind === 'remove' ? '-' : ' '}${row.text}`).join('\n')}`) }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>数据工具 / DIFF</p><h2>文本差异对比</h2><span>按行比较两段文本；绿色为新增、红色为删除、白色为未变内容。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="json-actions"><button :disabled="!diffRows.length || diffTooLarge" @click="copyDiff">复制统一 Diff</button><small class="diff-summary">{{ diffTooLarge ? '内容过长：两侧总行数需不超过 2000 行' : `共 ${diffRows.length} 行差异结果` }}</small></section><section class="json-editors diff-editors"><label>原始文本<textarea v-model="diffLeft" spellcheck="false" placeholder="粘贴原始文本"></textarea></label><label>目标文本<textarea v-model="diffRight" spellcheck="false" placeholder="粘贴目标文本"></textarea></label></section><section class="diff-result" aria-label="差异结果"><p v-for="(row, index) in diffRows" :key="index" :class="row.kind"><b>{{ row.kind === 'add' ? '+' : row.kind === 'remove' ? '−' : ' ' }}</b><code>{{ row.text || ' ' }}</code></p></section></ToolboxPage></template>
