<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
import SvgIcon from '../components/SvgIcon.vue'
const router = useRouter(); const imageInput = ref<HTMLInputElement>(); const imagePreviewUrl = ref(''); const imageFile = ref<File>(); const imageInfo = ref<{ width: number; height: number }>(); const imageMessage = ref('选择一张本地图片后，可预览并导出 PNG 或 JPEG。'); const imageCrop = ref({ x: 0, y: 0, width: 0, height: 0 }); const compressedImage = ref<{ url: string; blob: Blob; format: string }>(); const maxImageFileSize = 100 * 1024 * 1024; const maxImagePixels = 12_000_000; let imageLoadRequest = 0
const backToPortal = () => router.push({ name: 'portal' }); const openImagePicker = () => imageInput.value?.click(); const isSupportedImageFile = (file: File) => ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/bmp', 'image/svg+xml'].includes(file.type.toLowerCase()) || /\.(png|jpe?g|webp|gif|bmp|svg)$/i.test(file.name); const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 ** 2 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 ** 2).toFixed(2)} MB`
const clearCompressedImage = () => { if (compressedImage.value?.url) URL.revokeObjectURL(compressedImage.value.url); compressedImage.value = undefined }
const loadCanvasImage = (url: string): Promise<HTMLImageElement> => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('图片加载失败')); image.src = url })
const loadImage = (file?: File) => { const request = ++imageLoadRequest; if (!file || !isSupportedImageFile(file)) { imageMessage.value = '请选择 PNG、JPEG、WebP、GIF、BMP 或 SVG 图片文件。'; return } if (file.size > maxImageFileSize) { imageMessage.value = '单张图片不能超过 100 MB。'; return } if (imagePreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(imagePreviewUrl.value); clearCompressedImage(); imageFile.value = file; imagePreviewUrl.value = URL.createObjectURL(file); const image = new Image(); image.onload = () => { if (request !== imageLoadRequest) return; if (!image.naturalWidth || !image.naturalHeight || image.naturalWidth * image.naturalHeight > maxImagePixels) { imageMessage.value = '图片像素过大，请使用不超过 1200 万像素的图片。'; imageFile.value = undefined; imageInfo.value = undefined; return } imageInfo.value = { width: image.naturalWidth, height: image.naturalHeight }; imageCrop.value = { x: 0, y: 0, width: image.naturalWidth, height: image.naturalHeight }; imageMessage.value = '图片已加载，所有处理仅在本机完成。' }; image.onerror = () => { imageMessage.value = '图片无法加载。请确认文件未损坏。' }; image.src = imagePreviewUrl.value }
const onImageSelected = (event: Event) => { const input = event.target as HTMLInputElement; loadImage(input.files?.[0]); input.value = '' }; const onImageDropped = (event: DragEvent) => { const file = event.dataTransfer?.files[0]; if (file) loadImage(file) }
const renderImageCanvas = async () => { if (!imagePreviewUrl.value || !imageInfo.value) throw new Error('请先选择图片'); const image = await loadCanvasImage(imagePreviewUrl.value); const integer = (value: number, fallback: number) => Number.isFinite(value) ? Math.floor(value) : fallback; const x = Math.max(0, Math.min(imageInfo.value.width - 1, integer(imageCrop.value.x, 0))); const y = Math.max(0, Math.min(imageInfo.value.height - 1, integer(imageCrop.value.y, 0))); const width = Math.max(1, Math.min(imageInfo.value.width - x, integer(imageCrop.value.width, imageInfo.value.width))); const height = Math.max(1, Math.min(imageInfo.value.height - y, integer(imageCrop.value.height, imageInfo.value.height))); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d'); if (!context) throw new Error('无法创建图片画布'); context.drawImage(image, x, y, width, height, 0, 0, width, height); return canvas }
const applyCrop = async () => { try { const canvas = await renderImageCanvas(); if (imagePreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(imagePreviewUrl.value); imagePreviewUrl.value = canvas.toDataURL('image/png'); imageInfo.value = { width: canvas.width, height: canvas.height }; imageCrop.value = { x: 0, y: 0, width: canvas.width, height: canvas.height }; clearCompressedImage(); imageMessage.value = '裁剪已应用。' } catch (error) { imageMessage.value = error instanceof Error ? error.message : String(error) } }
const compressImage = async () => { try { clearCompressedImage(); const canvas = await renderImageCanvas(); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((result) => result ? resolve(result) : reject(new Error('图片编码失败')), 'image/png')); compressedImage.value = { url: URL.createObjectURL(blob), blob, format: 'image/png' }; imageMessage.value = '裁剪结果已生成。' } catch (error) { imageMessage.value = error instanceof Error ? error.message : String(error) } }
const downloadCompressedImage = () => { if (!compressedImage.value) return; const link = document.createElement('a'); link.href = compressedImage.value.url; link.download = `${imageFile.value?.name.replace(/\.[^.]+$/, '') ?? 'image'}-tinied.png`; link.click() }
onBeforeUnmount(() => { if (imagePreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(imagePreviewUrl.value); clearCompressedImage() })
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>设计工具 / CROP</p><h2>图片裁剪</h2><span>按像素精确裁剪本地图片，裁剪后可直接下载结果。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><input ref="imageInput" class="visually-hidden" type="file" accept="image/*" @change="onImageSelected"><section class="image-dropzone" :class="{ 'has-image': imagePreviewUrl }" @click="openImagePicker" @dragover.prevent @drop.prevent="onImageDropped"><img v-if="imagePreviewUrl" :src="imagePreviewUrl" :alt="imageFile?.name ?? '图片预览'"><div v-else><SvgIcon name="image" /><strong>选择或拖入图片</strong><span>支持常见图片格式</span></div></section><p class="tool-message">{{ imageMessage }}</p><section v-if="imageFile && imageInfo" class="image-workbench single-image-tool"><div><h3>裁剪区域</h3><p>设置裁剪区域后先应用，再下载处理结果。</p><label>X <input v-model.number="imageCrop.x" type="number" min="0" :max="Math.max(0, imageInfo.width - 1)"></label><label>Y <input v-model.number="imageCrop.y" type="number" min="0" :max="Math.max(0, imageInfo.height - 1)"></label><label>宽 <input v-model.number="imageCrop.width" type="number" min="1" :max="imageInfo.width - imageCrop.x"></label><label>高 <input v-model.number="imageCrop.height" type="number" min="1" :max="imageInfo.height - imageCrop.y"></label><button class="primary" @click="applyCrop">应用裁剪</button><button @click="compressImage">生成下载文件</button></div></section><section v-if="compressedImage && imageFile" class="compression-result"><div><small>裁剪结果</small><strong>{{ formatBytes(compressedImage.blob.size) }}</strong></div><button class="primary" @click="downloadCompressedImage">下载图片</button></section></ToolboxPage></template>
