<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const networkHost = ref('example.com'); const networkPort = ref(443); const networkMode = ref<'tcp' | 'http' | 'https'>('https'); const networkDiagnosis = ref<NetworkDiagnosis>(); const networkDiagnosisState = ref<'idle' | 'checking' | 'error'>('idle'); const networkDiagnosisMessage = ref('解析 DNS，并测试指定 TCP 端口能否连通。'); const backToPortal = () => router.push({ name: 'portal' })
const runNetworkDiagnosis = async () => { if (!window.networkTools) { networkDiagnosisState.value = 'error'; networkDiagnosisMessage.value = '网络诊断组件未加载，请重启应用。'; return } if (!networkHost.value.trim()) { networkDiagnosisState.value = 'error'; networkDiagnosisMessage.value = '请输入域名或 IP 地址。'; return } if (!Number.isInteger(networkPort.value) || networkPort.value < 1 || networkPort.value > 65_535) { networkDiagnosisState.value = 'error'; networkDiagnosisMessage.value = '端口必须是 1 到 65535 之间的整数。'; return } networkDiagnosisState.value = 'checking'; networkDiagnosisMessage.value = '正在解析 DNS 并测试 TCP 连接…'; try { networkDiagnosis.value = await window.networkTools.diagnose(networkHost.value, networkPort.value, networkMode.value); networkDiagnosisState.value = 'idle'; networkDiagnosisMessage.value = !networkDiagnosis.value.tcp.reachable ? `诊断完成，但目标端口不可连接：${networkDiagnosis.value.tcp.error ?? '未知原因'}` : networkDiagnosis.value.http && !networkDiagnosis.value.http.reachable ? `TCP 连接成功，但 ${networkDiagnosis.value.mode.toUpperCase()} 请求失败：${networkDiagnosis.value.http.error ?? '未知原因'}` : '诊断完成，所选探测均成功。' } catch (error) { networkDiagnosis.value = undefined; networkDiagnosisState.value = 'error'; networkDiagnosisMessage.value = error instanceof Error ? error.message : String(error) } }
const copyNetworkDiagnosis = async () => { if (!networkDiagnosis.value) return; const result = networkDiagnosis.value; await navigator.clipboard.writeText([`主机: ${result.host}`, `端口: ${result.port}`, `DNS: ${result.addresses.join(', ') || result.dnsError || '未返回地址'}`, `IPv4: ${result.ipv4.join(', ') || '未返回记录'}`, `IPv6: ${result.ipv6.join(', ') || '未返回记录'}`, `TCP: ${result.tcp.reachable ? `连接成功${result.tcp.latencyMs === undefined ? '' : ` (${result.tcp.latencyMs} ms)`}` : `无法连接 (${result.tcp.error ?? '未知原因'})`}`, result.http ? `${result.mode.toUpperCase()}: ${result.http.reachable ? `${result.http.status} ${result.http.statusText ?? ''} (${result.http.latencyMs} ms)` : `请求失败 (${result.http.error ?? '未知原因'})`}` : ''].filter(Boolean).join('\n')); networkDiagnosisMessage.value = '诊断结果已复制到剪贴板。' }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>网络工具 / DNS、TCP 与 HTTP</p><h2>网络诊断</h2><span>检查域名解析结果，并从本机测试 TCP 及可选的 HTTP/HTTPS 连通性。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="network-form"><label>域名或 IP<input v-model.trim="networkHost" placeholder="例如 api.example.com"></label><label>端口<input v-model.number="networkPort" type="number" min="1" max="65535"></label><label>探测方式<select v-model="networkMode"><option value="tcp">TCP（Telnet 类）</option><option value="http">HTTP</option><option value="https">HTTPS</option></select></label><button class="primary" :disabled="networkDiagnosisState === 'checking'" @click="runNetworkDiagnosis">{{ networkDiagnosisState === 'checking' ? '诊断中…' : '开始诊断' }}</button><button :disabled="!networkDiagnosis" @click="copyNetworkDiagnosis">复制诊断结果</button></section><p class="tool-message" :class="{ error: networkDiagnosisState === 'error' }">{{ networkDiagnosisMessage }}</p><section v-if="networkDiagnosis" class="results-card diagnosis-results"><div><h3>DNS 解析</h3><p :class="{ 'network-failed': networkDiagnosis.dnsError }">{{ networkDiagnosis.addresses.join(' · ') || networkDiagnosis.dnsError || '未返回地址' }}</p></div><div><h3>IPv4 记录</h3><p>{{ networkDiagnosis.ipv4.join(' · ') || '未返回记录' }}</p></div><div><h3>IPv6 记录</h3><p>{{ networkDiagnosis.ipv6.join(' · ') || '未返回记录' }}</p></div><div><h3>TCP {{ networkDiagnosis.port }}</h3><p :class="{ 'network-failed': !networkDiagnosis.tcp.reachable }">{{ networkDiagnosis.tcp.reachable ? `连接成功 · ${networkDiagnosis.tcp.latencyMs} ms` : `无法连接 · ${networkDiagnosis.tcp.error}` }}</p></div><div v-if="networkDiagnosis.http"><h3>{{ networkDiagnosis.mode.toUpperCase() }} 请求</h3><p :class="{ 'network-failed': !networkDiagnosis.http.reachable }">{{ networkDiagnosis.http.reachable ? `${networkDiagnosis.http.status} ${networkDiagnosis.http.statusText} · ${networkDiagnosis.http.latencyMs} ms` : `请求失败 · ${networkDiagnosis.http.error}` }}</p></div></section></ToolboxPage></template>
