<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const listeningProcesses = ref<ListeningProcess[]>([]); const portQuery = ref(''); const portState = ref<'idle' | 'loading' | 'terminating' | 'error'>('idle'); const portMessage = ref('查询当前 Windows 上正在监听的 TCP 端口。'); const backToPortal = () => router.push({ name: 'portal' })
const filteredListeningProcesses = computed(() => { const query = portQuery.value.trim().toLowerCase(); return query ? listeningProcesses.value.filter((process) => `${process.port} ${process.name} ${process.pid} ${process.address}`.toLowerCase().includes(query)) : listeningProcesses.value })
const refreshListeningProcesses = async () => { if (!window.processTools) return; portState.value = 'loading'; portMessage.value = '正在读取监听端口…'; try { listeningProcesses.value = await window.processTools.listListening(); portState.value = 'idle'; portMessage.value = `已找到 ${listeningProcesses.value.length} 个监听端口。` } catch (error) { portState.value = 'error'; portMessage.value = error instanceof Error ? error.message : String(error) } }
const terminateProcess = async (process: ListeningProcess) => { if (!window.processTools || !window.confirm(`将强制结束 ${process.name}（PID ${process.pid}），其子进程也会终止。是否继续？`)) return; portState.value = 'terminating'; try { await window.processTools.terminate(process.pid); portMessage.value = `已结束 ${process.name}（PID ${process.pid}）。`; await refreshListeningProcesses() } catch (error) { portState.value = 'error'; portMessage.value = error instanceof Error ? error.message : String(error) } }
void refreshListeningProcesses()
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>网络工具 / 本机进程</p><h2>端口与进程管理</h2><span>查看正在监听 TCP 端口的进程；结束进程前始终要求明确确认。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><section class="network-form"><label>筛选端口、进程名或 PID<input v-model.trim="portQuery" placeholder="例如 5173、node、12345"></label><button class="primary" :disabled="portState === 'loading' || portState === 'terminating'" @click="refreshListeningProcesses">{{ portState === 'loading' ? '刷新中…' : '刷新端口列表' }}</button><p class="tool-message" :class="{ error: portState === 'error' }">{{ portMessage }}{{ portQuery ? ` 当前显示 ${filteredListeningProcesses.length} 项。` : '' }}</p></section><section v-if="filteredListeningProcesses.length" class="results-card port-results"><div class="port-table"><div class="port-row port-head"><span>端口</span><span>地址</span><span>进程</span><span>操作</span></div><div v-for="process in filteredListeningProcesses" :key="`${process.protocol}-${process.address}-${process.port}-${process.pid}`" class="port-row"><code>{{ process.protocol }} :{{ process.port }}</code><code>{{ process.address }}</code><span>{{ process.name }} <small>PID {{ process.pid }}</small></span><button class="danger" :disabled="portState === 'terminating'" @click="terminateProcess(process)">结束进程</button></div></div></section><p v-else-if="portState === 'idle'" class="empty-state">{{ portQuery ? '没有匹配的监听端口。' : '当前没有可显示的 TCP 监听端口。' }}</p></ToolboxPage></template>
