<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import QRCode from 'qrcode'
import jsQR from 'jsqr'
import ToolboxPage from '../ToolboxPage.vue'
const router = useRouter(); const qrText = ref('https://localforge.app'); const qrImage = ref(''); const qrMessage = ref('输入文本或 URL 后生成二维码，也可选择图片识别二维码。'); const qrInput = ref<HTMLInputElement>(); const backToPortal = () => router.push({ name: 'portal' })
const generateQr = async () => { try { if (!qrText.value.trim()) throw new Error('请输入要编码的文本或 URL'); qrImage.value = await QRCode.toDataURL(qrText.value, { errorCorrectionLevel: 'M', margin: 2, width: 360, color: { dark: '#173b2a', light: '#ffffff' } }); qrMessage.value = '二维码已生成，内容未离开本机。' } catch (error) { qrImage.value = ''; qrMessage.value = `生成失败：${error instanceof Error ? error.message : String(error)}` } }
const downloadQr = () => { if (!qrImage.value) return; const link = document.createElement('a'); link.href = qrImage.value; link.download = 'localforge-qrcode.png'; link.click() }
const scanQr = (file?: File) => { if (!file || !(['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/bmp', 'image/svg+xml'].includes(file.type.toLowerCase()) || /\.(png|jpe?g|webp|gif|bmp|svg)$/i.test(file.name))) { qrMessage.value = '请选择 PNG、JPEG、WebP、GIF、BMP 或 SVG 图片。'; return } if (file.size > 50 * 1024 * 1024) { qrMessage.value = '二维码图片不能超过 50 MB。'; return } const image = new Image(); const url = URL.createObjectURL(file); image.onload = () => { if (!image.naturalWidth || !image.naturalHeight || image.naturalWidth * image.naturalHeight > 100_000_000) { qrMessage.value = '图片尺寸过大，请使用不超过 1 亿像素的图片。'; URL.revokeObjectURL(url); return } const canvas = document.createElement('canvas'); const scale = Math.min(1, 2_048 / Math.max(image.naturalWidth, image.naturalHeight)); canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale)); const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) { qrMessage.value = '无法读取图片像素。'; URL.revokeObjectURL(url); return } context.drawImage(image, 0, 0, canvas.width, canvas.height); const code = jsQR(context.getImageData(0, 0, canvas.width, canvas.height).data, canvas.width, canvas.height); qrMessage.value = code ? '已识别二维码内容。' : '未在图片中发现可识别的二维码。'; if (code) qrText.value = code.data; URL.revokeObjectURL(url) }; image.onerror = () => { qrMessage.value = '图片加载失败。'; URL.revokeObjectURL(url) }; image.src = url }
const onQrSelected = (event: Event) => { const input = event.target as HTMLInputElement; scanQr(input.files?.[0]); input.value = '' }
</script>
<template><ToolboxPage><header class="toolbox-heading"><div><p>设计工具 / QR CODE</p><h2>二维码工具</h2><span>生成二维码或从本地图片中识别内容，处理过程不经过网络。</span></div><button class="back-button" @click="backToPortal">‹ 返回工具列表</button></header><input ref="qrInput" class="visually-hidden" type="file" accept="image/*" @change="onQrSelected"><section class="qr-card"><label>二维码内容<textarea v-model="qrText" spellcheck="false" placeholder="输入文本或 URL"></textarea></label><div class="qr-actions"><button class="primary" @click="generateQr">生成二维码</button><button @click="qrInput?.click()">识别本地图片</button><button :disabled="!qrImage" @click="downloadQr">下载 PNG</button></div><p class="tool-message">{{ qrMessage }}</p><img v-if="qrImage" :src="qrImage" alt="生成的二维码"></section></ToolboxPage></template>
